<?php
/**
 * @file
 * CKEditor5 Highlight
 */

/**
 * Implements hook_ckeditor5_plugins().
 *
 */
function ckeditor5_plugin_pack_media_embed_ckeditor5_plugins() {
  $module_path = backdrop_get_path('module', 'ckeditor5_plugin_pack_media_embed');

  $plugins['mediaEmbed.MediaEmbed'] = array(
    'buttons' => array(
      'mediaEmbed' => array(
        'label' => t('Insert media'),
        'image' => $module_path . '/icons/media.svg',
        'required_html' => array(
          '<figure>',
          '<figure class>',
          '<oembed>',
        ),
        'plugin_dependencies' => array(
          'mediaEmbed.MediaEmbed',
        ),
        'config' => array(
          'mediaEmbed' => array(
            'previewsInData' => FALSE,
            'removeProviders' => array(
              'facebook',
              'instagram',
              'twitter',
            ),
          ),
        ),
      ),
    ),
  );

  return $plugins;

}
