<?php
/**
 * @file
 * CKEditor5 Highlight
 */

/**
 * Implements hook_ckeditor5_plugins().
 *
 */
function ckeditor5_plugin_pack_media_embed_ckeditor5_plugins() {
  $module_path = backdrop_get_path('module', 'ckeditor5_plugin_pack_media_embed');

  $plugins['mediaEmbed.MediaEmbed'] = array(
    'buttons' => array(
      'mediaEmbed' => array(
        'label' => t('Insert media'),
        'image' => $module_path . '/icons/media.svg',
        'required_html' => array(
          '<figure>',
          '<figure class>',
          // '<iframe>',
          // '<iframe src allow allowfullscreen frameborder>',
          '<div>',
          '<div data-oembed-url>',
          '<oembed>',
        ),
      ),
    ),
    'plugin_dependencies' => array(
      'mediaEmbed.MediaEmbed',
    ),
    'config' => array(
      'mediaEmbed' => array(
        'previewsInData' => TRUE,
        'removeProviders' => array(
          'facebook',
          'instagram',
          'twitter',
        ),
      ),
    ),
    'enabled_callback' => TRUE,
  );

  return $plugins;

}

// Mention video_filter could parse oembed. Or include it here?
